services:
  - type: web
    name: resume-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn resume_api:app --host 0.0.0.0 --port 10000
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
